// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUW6AuKCfBxCEwVf5QSoMDqLBIApYZq8I',
    appId: '1:520836768759:web:791760e46f406b937604f2',
    messagingSenderId: '520836768759',
    projectId: 'loginui-b0e63',
    authDomain: 'loginui-b0e63.firebaseapp.com',
    storageBucket: 'loginui-b0e63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrxOlwuAjjljANm1nw1SmrMX0tUEhHNNU',
    appId: '1:520836768759:android:d63ba394f833040a7604f2',
    messagingSenderId: '520836768759',
    projectId: 'loginui-b0e63',
    storageBucket: 'loginui-b0e63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1qeNqMO10C4gNrN84GywZh8Rr3T9Z3a8',
    appId: '1:520836768759:ios:7a8656a32963a4c87604f2',
    messagingSenderId: '520836768759',
    projectId: 'loginui-b0e63',
    storageBucket: 'loginui-b0e63.appspot.com',
    iosClientId: '520836768759-bmd576n1e3anjaqt8ko3a02re4ssg0ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1qeNqMO10C4gNrN84GywZh8Rr3T9Z3a8',
    appId: '1:520836768759:ios:7a8656a32963a4c87604f2',
    messagingSenderId: '520836768759',
    projectId: 'loginui-b0e63',
    storageBucket: 'loginui-b0e63.appspot.com',
    iosClientId: '520836768759-bmd576n1e3anjaqt8ko3a02re4ssg0ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginui',
  );
}
